import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
  {
    orderSn: {
      type: String,
      required: true,
      unique: true,
    },

    // Relations
    merchant: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Merchant",
      required: true,
    },
    dispatchedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // Products in this order
    products: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Product",
        },
        title: String,
        image: String,
        quantity: Number,
        price: Number,
      },
    ],

    // Fake buyer info (auto-generated by dispatch admin)
    buyerName: {
      type: String,
      default: "",
    },
    buyerUserId: {
      type: Number,
      default: 0,
    },
    shippingAddress: {
      type: String,
      default: "",
    },
    phoneNumber: {
      type: String,
      default: "",
    },
    country: {
      type: String,
      default: "",
    },

    // Financials
    totalCost: {
      type: Number,
      required: true, // merchant pays this (cost price total)
    },
    sellingPrice: {
      type: Number,
      required: true, // the selling price total
    },
    earnings: {
      type: Number,
      default: 0, // profit = sellingPrice - totalCost
    },

    // Order type
    orderType: {
      type: String,
      default: "Virtual Order",
    },

    // Status flow
    status: {
      type: String,
      enum: [
        "pendingPayment", // waiting for merchant to pickup
        "pendingShipment", // merchant picked up, waiting for shipment
        "shipped", // shipped
        "received", // buyer received
        "completed", // super admin confirmed profit
        "cancelled",
        "refunding",
      ],
      default: "pendingPayment",
    },

    frozenStatus: {
      type: String,
      default: "normal",
    },

    // Countdown timer (set by dispatch admin, 1-10 days)
    completionDays: {
      type: Number,
      default: 1,
    },
    pickupDeadline: {
      type: Date,
      default: null, // set when order is assigned
    },
    pickedUpAt: {
      type: Date,
      default: null,
    },
    completedAt: {
      type: Date,
      default: null,
    },

    // Logistics
    trackingNumber: {
      type: String,
      default: "",
    },
    logisticsInfo: [
      {
        status: String,
        time: Date,
      },
    ],

    // Profit confirmed by super admin?
    profitConfirmed: {
      type: Boolean,
      default: false,
    },
    profitConfirmedAt: {
      type: Date,
      default: null,
    },

    // Refund
    isRefunded: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  },
);

const Order = mongoose.model("Order", orderSchema);
export default Order;
